"""
Data models for the entire pipeline.
Every piece of data flowing through the system has a strict shape.
"""

from pydantic import BaseModel, Field
from typing import Optional
from enum import Enum
from datetime import datetime


# ============================================================
# Enums
# ============================================================

class JobStatus(str, Enum):
    QUEUED = "queued"
    DOWNLOADING = "downloading"
    EXTRACTING_AUDIO = "extracting_audio"
    TRANSCRIBING = "transcribing"
    ANALYZING_TONE = "analyzing_tone"
    ANALYZING_FACE = "analyzing_face"
    GENERATING_RESUME = "generating_resume"
    GENERATING_PDF = "generating_pdf"
    GENERATING_CLIP = "generating_clip"
    UPLOADING_RESULTS = "uploading_results"
    COMPLETED = "completed"
    FAILED = "failed"


# ============================================================
# API Request / Response
# ============================================================

class ProcessVideoRequest(BaseModel):
    video_url: str = Field(..., description="Cloudinary URL of uploaded video")
    submission_id: str = Field(..., description="Supabase submission record ID")
    user_id: str = Field(..., description="Supabase user ID")
    user_name: str = Field(default="Student", description="Student's full name")
    user_university: str = Field(default="", description="University name")
    user_branch: str = Field(default="", description="Branch/department")
    user_year: int = Field(default=1, description="Year of study")


class ProcessVideoResponse(BaseModel):
    job_id: str
    status: JobStatus
    message: str


class JobStatusResponse(BaseModel):
    job_id: str
    status: JobStatus
    progress: int = Field(default=0, ge=0, le=100)
    message: str = ""
    result: Optional["ProcessingResult"] = None
    error: Optional[str] = None


class HealthResponse(BaseModel):
    status: str = "healthy"
    version: str = "1.0.0"
    services: dict = {}


# ============================================================
# Internal Pipeline Data
# ============================================================

class AudioAnalysis(BaseModel):
    """Output from librosa tone analysis."""
    average_energy: float = 0.0
    energy_std: float = 0.0
    speaking_rate_wpm: float = 0.0
    pitch_mean: float = 0.0
    pitch_std: float = 0.0
    confidence_score: float = 0.0      # 0-100, derived from energy + pitch stability
    energy_timeline: list[float] = []   # per-second energy values for highlight selection


class FaceAnalysis(BaseModel):
    """Output from MediaPipe face analysis."""
    face_detected: bool = False
    face_detection_confidence: float = 0.0
    avg_eye_contact_score: float = 0.0  # 0-100
    avg_expression_score: float = 0.0   # 0-100, based on smile/engagement
    expression_timeline: list[float] = []  # per-second expression scores


class TranscriptSegment(BaseModel):
    """A timed segment of the transcript."""
    start: float
    end: float
    text: str


class TranscriptionResult(BaseModel):
    """Output from Groq Whisper."""
    full_text: str = ""
    segments: list[TranscriptSegment] = []
    language: str = "en"
    duration: float = 0.0


class ResumeData(BaseModel):
    """Structured resume generated by LLM."""
    summary: str = ""
    skills: list[str] = []
    experience: list[dict] = []
    education: list[dict] = []
    projects: list[dict] = []
    achievements: list[str] = []


class HighlightSelection(BaseModel):
    """The selected 30-second window for the highlight clip."""
    start_time: float
    end_time: float
    score: float
    reason: str


class ProcessingResult(BaseModel):
    """Final output after full pipeline completes."""
    transcript: str = ""
    resume_pdf_url: str = ""
    highlight_clip_url: str = ""
    confidence_score: float = 0.0
    energy_score: float = 0.0
    expression_score: float = 0.0
    eye_contact_score: float = 0.0
    skills_extracted: list[str] = []
    highlight_start: float = 0.0
    highlight_end: float = 0.0


# Forward ref fix
JobStatusResponse.model_rebuild()
